### ISSUE TITLE
Appears to not retry process that threw an error

### ISSUE THREAD

**Issue by rclark** [mapbox/ecs-watchbot#10]
For example:

```
[Fri, 13 May 2016 16:02:47 GMT] /.../node_modules/aws-sdk/lib/request.js:31
[Fri, 13 May 2016 16:02:47 GMT]             throw err;
[Fri, 13 May 2016 16:02:47 GMT]             ^
[Fri, 13 May 2016 16:02:47 GMT] InvalidArgument: Unable to validate the following destination configurations
[Fri, 13 May 2016 16:02:47 GMT]     at Request.extractError (/.../node_modules/aws-sdk/lib/services/s3.js:350:35)
[Fri, 13 May 2016 16:02:47 GMT]     at Request.callListeners (/.../node_modules/aws-sdk/lib/sequential_executor.js:105:20)
[Fri, 13 May 2016 16:02:47 GMT]     at Request.emit (/.../node_modules/aws-sdk/lib/sequential_executor.js:77:10)
[Fri, 13 May 2016 16:02:47 GMT]     at Request.emit (/.../node_modules/aws-sdk/lib/request.js:615:14)
[Fri, 13 May 2016 16:02:47 GMT]     at Request.transition (/.../node_modules/aws-sdk/lib/request.js:22:10)
[Fri, 13 May 2016 16:02:47 GMT]     at AcceptorStateMachine.runTo (/.../node_modules/aws-sdk/lib/state_machine.js:14:12)
[Fri, 13 May 2016 16:02:47 GMT]     at /.../node_modules/aws-sdk/lib/state_machine.js:26:10
[Fri, 13 May 2016 16:02:47 GMT]     at Request.<anonymous> (/.../node_modules/aws-sdk/lib/request.js:38:9)
[Fri, 13 May 2016 16:02:47 GMT]     at Request.<anonymous> (/.../node_modules/aws-sdk/lib/request.js:617:12)
[Fri, 13 May 2016 16:02:47 GMT]     at Request.callListeners (/.../node_modules/aws-sdk/lib/sequential_executor.js:115:18)
[Fri, 13 May 2016 16:03:06 GMT] [info] [watchbot] [fc91ac21-8511-4b87-ae8c-853a8fac18d0] finished | outcome: delete
```

**Comment by rclark** [comment]
This had to do with a misconfiguration in a dockerfile.
