### ISSUE TITLE
Troubleshooting dead-letter command

### ISSUE THREAD

**Issue by GretaCB** [mapbox/ecs-watchbot#253]
Hey @jakepruitt 👋 , I've been attempting to get the `dead-letter` command working in my local env, and ultimately was able to get it working. Though, I'm including all my steps below to give you more info in case anyone else hits the same issues.

#### I had watchbot `3.4.0` already installed
```
gretacb:unpacker carol$ ./node_modules/.bin/watchbot --version
3.4.0
```
When attempting to call `dead-letter` with this version, I was hitting a few dep errors:
```
gretacb:unpacker carol$ ./node_modules/.bin/watchbot dead-letter
Cannot find module 'p-queue'
...
gretacb:unpacker carol$ npm install p-queue
+ p-queue@2.4.2
added 1 package in 11.406s
gretacb:unpacker carol$ ./node_modules/.bin/watchbot dead-letter
Cannot find module 'cli-spinner'
...
gretacb:unpacker carol$ npm install cli-spinner
+ cli-spinner@0.2.8
added 1 package in 11.092s
```
Which I installed, and then attempted the entire dead-letter command:
```
gretacb:unpacker carol$ ./node_modules/.bin/watchbot dead-letter --stack-name unpacker-production --region us-east-1
? Would you like to: (Use arrow keys)
❯ Triage dead messages individually? 
  Print out all dead messages? 
  Return all dead messages to the work queue? 
  Purge the dead letter queue? TypeError: inquirer.prompt(...).then is not a function
    at triageSelection (/Users/carol/dev/unpacker/node_modules/@mapbox/watchbot/lib/dead-letter.js:91:6)
    at findQueues.then.then (/Users/carol/dev/unpacker/node_modules/@mapbox/watchbot/lib/dead-letter.js:18:22)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)

  Helper utilities for interacting with watchbot stacks

  USAGE: watchbot <command> [OPTIONS]

  Commands:
    worker-capacity     assess available resources on the cluster
    dead-letter         triage messages in dead letter queue

  Options:
    -h, --help          show this help message
    -s, --stack-name    the full name of a watchbot stack
    -r, --region        the region of the stack (default us-east-1)
  
```
which immediately crashed, not allowing me to choose any of the options.

#### I tried watchbot `3.5.1`
```
gretacb:unpacker carol$ npm install -g @mapbox/watchbot@3.5.1
npm WARN deprecated dyno@1.4.1: This module has been moved. Please install @mapbox/dyno instead
npm WARN deprecated queue-async@1.0.7: renamed to d3-queue
/Users/carol/.nvm/versions/node/v6.14.3/bin/watchbot-progress -> /Users/carol/.nvm/versions/node/v6.14.3/lib/node_modules/@mapbox/watchbot/bin/watchbot-progress.sh
/Users/carol/.nvm/versions/node/v6.14.3/bin/watchbot-log -> /Users/carol/.nvm/versions/node/v6.14.3/lib/node_modules/@mapbox/watchbot/bin/watchbot-log.js
/Users/carol/.nvm/versions/node/v6.14.3/bin/watchbot -> /Users/carol/.nvm/versions/node/v6.14.3/lib/node_modules/@mapbox/watchbot/bin/cli.js
+ @mapbox/watchbot@3.5.1
added 91 packages in 5.996s
```
I then attempted to call the `dead-letter` command using the absolute path described during the install:
```
gretacb:unpacker carol$ /Users/carol/.nvm/versions/node/v6.14.3/bin/watchbot dead-letter --stack-name unpacker-production --region us-east-1
"dead-letter" is not a valid command

  Helper utilities for interacting with watchbot stacks

  USAGE: watchbot <command> [OPTIONS]

  Commands:
    worker-capacity     assess available resources on the cluster
    dead-letter         triage messages in dead letter queue

  Options:
    -h, --help          show this help message
    -s, --stack-name    the full name of a watchbot stack
    -r, --region        the region of the stack (default us-east-1)
  
gretacb:unpacker carol$ /Users/carol/.nvm/versions/node/v6.14.3/bin/watchbot --version
3.5.1
gretacb:unpacker carol$ watchbot --version
3.5.1
gretacb:unpacker carol$ watchbot dead-letter
"dead-letter" is not a valid command ...
```

#### I tried watchbot `4.6.0`

```
gretacb:unpacker carol$ npm install -g @mapbox/watchbot
/Users/carol/.nvm/versions/node/v6.14.3/bin/watchbot -> /Users/carol/.nvm/versions/node/v6.14.3/lib/node_modules/@mapbox/watchbot/bin/watchbot.js
/Users/carol/.nvm/versions/node/v6.14.3/bin/watchbot-dead-letter -> /Users/carol/.nvm/versions/node/v6.14.3/lib/node_modules/@mapbox/watchbot/bin/dead-letter.js
+ @mapbox/watchbot@4.6.0
added 55 packages, removed 61 packages and updated 1 package in 8.562s
gretacb:unpacker carol$ watchbot-dead-letter --help
/Users/carol/.nvm/versions/node/v6.14.3/lib/node_modules/@mapbox/watchbot/bin/dead-letter.js:15
const main = async () => {
                   ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)
gretacb:unpacker carol$ node -v
v6.14.3
gretacb:unpacker carol$ npm -v
5.6.0
```
Is this `async` command a special ES6 thing that my node version doesn't like? Do I need node 8/10?

...I upgraded to node 8, and the async error went away 👍 . I then had to manually `-g` install a few deps:
- meow
- cli-spinner
- cwlogs

and voila 🎉 ...
```
gretacb:unpacker carol$ watchbot-dead-letter --stack-name unpacker-production --region us-east-1
? Would you like to: (Use arrow keys)
❯ Triage dead messages individually? 
  Print out all dead messages? 
  Return all dead messages to the work queue? 
  Purge the dead letter queue? 
```

So, looks like I'm all set, but I will need to ensure Node 8, and not sure why the three deps weren't initially included.

**Comment by GretaCB** [comment]
Closing.
