### ISSUE TITLE
watchbot-dead-letter's "View this message's recent logs?" functionality throws an error and exits the command

### ISSUE THREAD

**Issue by jseppi** [mapbox/ecs-watchbot#350]
In the `watchbot-dead-letter` command, when I selected:
- `Triage dead messages individually?`
- `View this message's recent logs?`

the command crashes with `InvalidParameterException: Invalid filter pattern`.

Full error stack, though probably not very helpful:

```
? Would you like to: View this message's recent logs?
⠆ Searching CloudWatch logs...InvalidParameterException: Invalid filter pattern
    at Request.extractError (/Users/jamesseppi/CODE/ecs-watchbot/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.callListeners (/Users/jamesseppi/CODE/ecs-watchbot/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/jamesseppi/CODE/ecs-watchbot/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/jamesseppi/CODE/ecs-watchbot/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/jamesseppi/CODE/ecs-watchbot/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/jamesseppi/CODE/ecs-watchbot/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/jamesseppi/CODE/ecs-watchbot/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/jamesseppi/CODE/ecs-watchbot/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/jamesseppi/CODE/ecs-watchbot/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/jamesseppi/CODE/ecs-watchbot/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
```

**Comment by rclark** [comment]
Pulling logs is done through an external dependency: https://github.com/mapbox/cwlogs. [Here is where the "filter pattern" is used to perform a search across CloudWatch Logs](https://github.com/mapbox/cwlogs/blob/15fd2140b52fff29c676c6d3972066235f5159e2/lib/readable.js#L52-L58). This is either a bug in watchbot (sending bad values to that library), or an upstream bug in cwlogs (using valid input to construct a bad request).

**Comment by jseppi** [comment]
Looks like exactly the same issue as https://github.com/mapbox/ecs-watchbot/issues/141. I think https://github.com/mapbox/ecs-watchbot/pull/220/files did not actually fix that particular issue.
