### ISSUE TITLE
The security token included in the request is expired

### ISSUE THREAD

**Issue by mick** [mapbox/ecs-watchbot#61]
Had a watchbot stack start hitting this error, repeatedly, ~30 times per min.  

Only 1 worker, jobs were still being run and completing successfully.  Only impacting resource polling.

```
[Wed, 12 Oct 2016 14:14:51 GMT] [watchbot] Error polling cluster resources: The security token included in the request is expired
[Wed, 12 Oct 2016 14:14:51 GMT] [watchbot] ExpiredToken: The security token included in the request is expired
    at Request.extractError (/usr/local/src/watchbot/node_modules/aws-sdk/lib/protocol/query.js:40:29)
    at Request.callListeners (/usr/local/src/watchbot/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/usr/local/src/watchbot/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/usr/local/src/watchbot/node_modules/aws-sdk/lib/request.js:668:14)
    at Request.transition (/usr/local/src/watchbot/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/src/watchbot/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/src/watchbot/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/src/watchbot/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/src/watchbot/node_modules/aws-sdk/lib/request.js:670:12)
    at Request.callListeners (/usr/local/src/watchbot/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    message: The security token included in the request is expired
    code: ExpiredToken
    requestId: e07645c9-b71f-5b38-b5e5-15b1f084d900
    statusCode: 403
```

cc @rclark @bkowshik

**Comment by rclark** [comment]
I wonder if this was an isolated incident, or if you've been able to reproduce it?

**Comment by mick** [comment]
Havent seen it since. That same watchbot is still running ok.

**Comment by bkowshik** [comment]
I too have not seen it since.

**Comment by rclark** [comment]
Going to close. Feel free to open if you can reproduce this again.
